Include huffmanca as an approver
openshift/csi-driver-manila-operator pull request #67
Opened 2020-09-29 15:48 UTC by huffmanca

Updated OWNERS file to add myself as an approver.

2020-09-29 15:49 UTC, jsafrane commented
It looks like an oversight
/lgtm
/approve

2020-09-29 15:51 UTC, Fedosin requested changes
Keep the list in alphabetical order, please :)

2020-09-29 16:11 UTC, huffmanca commented
@Fedosin ,

Apologies. This has been corrected.

2020-09-30 07:36 UTC, jsafrane commented
/lgtm

2020-09-30 07:39 UTC, merged